# Use Ubuntu Xenial-based lamp-web images
FROM public.ecr.aws/uazgraduatecollege/lamp-web:php-7.4

# Install dev dependencies and vim
RUN apt update && apt install -y \
      php-pcov \
      php-xdebug \
      vim

# Metadata
LABEL org.label-schema.tag = "php-7.4-xdebug"

